repos:
- repo: local
  hooks:
  - id: ruff
    name: ruff
    entry: rye run ruff --fix
    language: system
    types: [python]
    require_serial: true
    files: ^(custom_components|tests)/.+\.py$
- repo: local
  hooks:
  - id: pyright
    name: pyright
    entry: rye run pyright
    language: system
    types: [python]
    require_serial: true
    files: ^(custom_components|tests)/.+\.pyi?$
