[project]
name = "hubitat"
version = "0.9.28"
description = "A Hubitat integration for Home Assistant"
authors = [{ name = "Jason Cheatham", email = "jason@jasoncheatham.com" }]
dependencies = [
    "pyright>=1.1.359",
]
requires-python = ">=3.12,<3.13"
license = { text = "MIT" }

[project.urls]
homepage = "https://github.com/jason0x43/hacs-hubitat"

[project.optional-dependencies]

[tool.rye.scripts]
test-lint = "pyright custom_components/hubitat"
test-test = "pytest tests"
test = { chain = ["test-lint", "test-test"] }
pub = "python scripts/publish.py"

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning:pkg_resources",
    "ignore:Inheritance class HomeAssistantApplication:DeprecationWarning",
]

[tool.rye]
dev-dependencies = [
    "ruff",
    "pre-commit<3.0.0,>=2.4.0",
    "homeassistant==2024.5.0b1",
    "pytest-asyncio>=0.16.0",
    "setuptools>=62.2.0",
    "tomlkit>=0.12.3",
]

[tool.pyright]
include = ["custom_components/hubitat"]
exclude = ["**/__pycache__"]
extraPaths = ["__pypackages__/3.9/lib"]
stubPath = "."
reportDuplicateImport = true
reportMissingImports = true
reportOptionalCall = true
reportOptionalMemberAccess = true
reportOptionalSubscript = true
reportUnusedClass = true
reportUnusedFunction = true
reportUnusedImport = true
reportUnusedVariable = true

[tool.ruff.lint]
select = ["E", "W", "F", "PYI", "I"]

[tool.ruff.lint.isort]
combine-as-imports = true
order-by-type = true
force-wrap-aliases = true
known-first-party = ["homeassistant", "tests"]
forced-separate = ["tests"]
